### ISSUE TITLE
[Feature Request] Ability to define multiple app ports

### ISSUE THREAD

**Issue by mimidotsuser** [crane-cloud/frontend#422]
Currently, a user can only define one port for an individual app/container. Sometimes an image might support multiple ports.
I am requesting support for the ability to define multiple ports.

**Comment by neelxie** [comment]
@mimidotsuser Thank you for the suggestion. Kindly note that we are guided on development by the product roadmap and this is something already planned for, sadly it is not part of the aspects we have to focus on for the now but rest assured we will have it soon enough.
