### ISSUE TITLE
Mobile Responsiveness

### ISSUE THREAD

**Issue by kallyas** [crane-cloud/frontend#643]
After visiting the site using my phone, I realized the content was over flowing on the y axis as shown below
![image](https://user-images.githubusercontent.com/60466044/216014019-b0d4d704-5fb6-4955-b957-a31e303cf8b3.png)

![image](https://user-images.githubusercontent.com/60466044/216014112-89552975-0fd7-4df9-b82b-7dcd1490da8b.png)

I would recommend to column the content on mobile devices instead of row

**Comment by neelxie** [comment]
@kallyas thanks for highlighting we already have a PR in the pipeline to fix just that. https://github.com/crane-cloud/frontend/pull/642
